#'''Parameters config.'''#


# --- binning_algorithms --- #

min_contig_len:   2500


# --- metabat2_binning --- #

min_metabat_len:  2500


# --- concoct_binning --- #

fragment_size:    10000
overlap_size:     0


# --- vamb_binning --- #

min_bin_size: 2500
# Test-only-values: '-e 2 -t 2 -q 1'
# Keep blank for actual runs
test_flags: ''


# --- semibin_binning --- #

model_environment: 'human_gut'


# --- maxbin2_binning --- #

maxbin2_script: ''


# --- das_tool_refinement --- #

ext: ''
