#'''Command-line usage resource config.'''#


# --- map_sort --- #

map_sort_threads: 20
map_sort_mem_mb: 40000


# --- metabat2_binning --- #

metabat2_binning_threads: 20
metabat2_binning_mem_mb: 80000


# --- concoct_binning --- #

concoct_binning_mem_mb: 80000


# --- semibin_binning --- #

semibin_binning_threads: 20
semibin_binning_mem_mb: 80000


# --- maxbin2_binning --- #

maxbin2_binning_threads: 20
maxbin2_binning_mem_mb: 80000


# --- dastool_refinement --- #

dastool_refinement_threads: 20
dastool_refinement_mem_mb: 80000